apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio-restore
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: nas-dev.example.internal
    path: /srv/nas/dev/uds/minio-restore
